import express from "express";
const router = express.Router();

var Secret_Key = 'sk_test_51P8mSISAiCspvlFuA3ZF9xLzwbzKNOruY2Dzm9Hjx6J6bnriE3tErLCzrZf5wtliD6oTMDVZZL0CDnkBfO1ZXfEd008dpnh0gY'

import Stripe from 'stripe';

const stripe = new Stripe(Secret_Key, {
    apiVersion: '2020-08-27', // Specify the Stripe API version (optional)
});

router.post('/payment', async (req, res) => {
    try {
        const { amount, currency, token } = req.body;

        // Create a charge using Stripe API
        const charge = await stripe.charges.create({
            amount,
            currency,
            source: token, // token generated by Stripe.js on the frontend
            description: 'Payment for products/services'
        });

        res.status(200).json({ success: true, message: 'Payment processed successfully' });
    } catch (error) {
        console.error('Error processing payment:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});


export default router;